//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoPagina1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.imagenproducto = new HashSet<imagenproducto>();
        }
    
        public int codigoproducto { get; set; }
        public int codigolineasubcategoria { get; set; }
        public string nombreproducto { get; set; }
        public string descripcionproducto { get; set; }
        public Nullable<decimal> precioproducto { get; set; }
        public string detallesproducto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imagenproducto> imagenproducto { get; set; }
        public virtual lineasubcategoria lineasubcategoria { get; set; }
    }
}
